#ENC[AES256_GCM,data:C+n6I+uyY7PJfVenPP1MLJjNdpscf3u2+9JUew==,iv:A84EMlgnuyuDYdS+Nxvhz9GdLk6UUTZDSzeD9xkP2bU=,tag:TxWeRiF+iYNd8SIIX/86nw==,type:comment]
#ENC[AES256_GCM,data:fPtC5mT/bV/ddoXVuQU+8nnHYA04BYdo6i7ozkixA5ZsERBA4G85YgMOOtwHAw==,iv:RwUkduqU6FUZR9JZTELQYE2HccTi2lRJNa/TEf0ebVU=,tag:Z61ZeVp6BmZ35lhDEbRijA==,type:comment]
#
#ENC[AES256_GCM,data:MIVHNueqhVNrDLR5R/QUju1m+wYplDKjHgk4WFNgZrKYyj+kww==,iv:eEWIb4BqtDwIi98JN8g39kTO7NKWGq03iOWYrEcxZr4=,tag:wipxSEzL6bJ06Pyfs15Erw==,type:comment]
#ENC[AES256_GCM,data:n3YR+iMAcAPETtoHZ5yuJlOUcJtwTddOruAUIb0vVkztAOb3gDygCBoT,iv:vt7FrBPBarXQOrKwCyZxbKUoQ5qCrDtosKAIuIEPSj8=,tag:ts+f6Qen1IC3Grf0rxUJ3Q==,type:comment]
#ENC[AES256_GCM,data:aBhbWLlwLjBDaL+oxtciFExapv8ThkDg65yHQzfwQyxAmSH4/lubB8FWjZj8,iv:SdQNFJHWv5Il09wb9Ou15qwvMkBDWyJ/wXToia5q9xA=,tag:KMPfW+6f8r3siRw6Pfe+Ug==,type:comment]
config:
    authelia:encryptionKey:
        secret: ENC[AES256_GCM,data:lYbP9w==,iv:XeKx00PGdAGilX4UIaHRGwtWWcTVxRD8cJz+dPkk05g=,tag:yKfomjNxbYPrMhBVxprnOw==,type:bool]
        value: ENC[AES256_GCM,data:Qb8q6Kaas8pU26ZL3xouuZ7fEfVsZ/rM8S9XOQ9zeTPjtXCXCdBvZ7eXZyuRGfKIGFBCkcUHBSDpe3cffBXpEDOe0FoHqn274m53WoNxekOTPE7QZM1zDw==,iv:fpGhkRkGNHj6nobfHUJmt6VIPBE/+wzKgP+hE73t/QI=,tag:cQFx5mhsGpH0DAQse1oA9Q==,type:str]
    authelia:jwtSecret:
        secret: ENC[AES256_GCM,data:u/ulng==,iv:bi0bBw08wZasw5UNFeIYePx4JrTBHslltjiVP8bk40M=,tag:Pwqv0hkFKIYCpwMPoP3Pxg==,type:bool]
        value: ENC[AES256_GCM,data:VO0=,iv:+OjXOtBbN/trqBBTYkFVswqyEVnR5JMmhMH58DYxeVs=,tag:wVWHCW8IWM51DVJ1cotBtA==,type:str]
    authelia:oidcPrivateKey:
        secret: ENC[AES256_GCM,data:P/e/Uw==,iv:YFz63SgWe2lrJngk91RTYBXsPm8iZIMvtgbzc8PgbT4=,tag:O5powTHw842U8CGryQPeyA==,type:bool]
        value: ENC[AES256_GCM,data:9TI=,iv:bl8HIY607E523ka6Ob05L06ShaZQPOLQYeVz9BrqiQ4=,tag:XnZsmm97ezDyBRLX4QQYWw==,type:str]
    authelia:sessionSecret:
        secret: ENC[AES256_GCM,data:zHICxg==,iv:bvqfWTTUeWxkFsTV3ntLv1Y5zXxErShcYD1x7WL1Jks=,tag:S2nW7l1yg6j309DrQtvALg==,type:bool]
        value: ENC[AES256_GCM,data:iHE=,iv:+3X1yzIORMqPkf2a1ALPtW7L7MW/pC4TpY4PPWny0Fs=,tag:uUoWudNoVzNxk5uw7hp9mg==,type:str]
    authelia:supabaseClientSecret:
        secret: ENC[AES256_GCM,data:dxM/dQ==,iv:f3+XLNt8UC8UIQTcbUV2i461zz3010QuFh1iP+8zzmA=,tag:IOB2p4nKbHMFHxpRG9iUOg==,type:bool]
        value: ENC[AES256_GCM,data:SSo=,iv:wqU+XgFDETQ4n6guoe9PL1MC6N03hVsBFUFPu7xqdFM=,tag:Q+33RKxf976t0jUiKs8n2A==,type:str]
    cloudflare:apiToken:
        secret: ENC[AES256_GCM,data:850ccA==,iv:1ZttLmCgopRlbAPsM9lD3Qg7+CUaCeu7BV5WysQgtsU=,tag:5Db36xPl1vrrGnqEIDUMIg==,type:bool]
        value: ENC[AES256_GCM,data:Ht8Y8m4L1V2P3Ls2V/6ewRbd18H/xw2x3jJ1s64AP/IvGcgvOj1XWw==,iv:61Fxx90wM95cHTx6X/PAyLzZxYtpcttd1auRNXjY51g=,tag:Hw6yGkPwPOP3R8FJTEndsg==,type:str]
    container-registry:domain:
        value: ENC[AES256_GCM,data:MyaE8IdmH96Jm/ekQYNA9R7Ygbzy,iv:a1rUI1dce4WQnpX+yxGTJtTUS2SWG+HhJ2DX7GmbvAs=,tag:CQxiAd+j1oT1xbEWKxDtzw==,type:str]
    container-registry:username:
        value: ENC[AES256_GCM,data:zfTxdD0=,iv:hK08C4yglWraUew3LUHd+2iMFbaRuEZROLgHN4Hgcxo=,tag:L8wVfLM8z2zpqkafOfA4DQ==,type:str]
    homelab:autheliaAdminPasswordHash:
        secret: ENC[AES256_GCM,data:vpxtLA==,iv:b6VJKr7cxnndFhqpFqb+tH3CAC8lj+vih57jnymx5/c=,tag:Ry0+URE0C41NpTzmdx4CsA==,type:bool]
        value: ENC[AES256_GCM,data:CR28mezuJr1syG4i4//SK75d1C2a6RDeBGx2jJvDusTyWn/BFr8jEwQVOAjR3bcquJs+6v1vPWvyoaJiRQeEioFAJwyq4JCNnWGNp3a217H6huxyl/YuPi7vS/ZldLlivA==,iv:9CwE8GRdeYt2qiNzw1HKOSAQaYkynWZ/wAMIYsqTmP4=,tag:847KIfiIXiRbdIXKtI49jw==,type:str]
    homelab:autheliaJwtSecret:
        secret: ENC[AES256_GCM,data:ESyEUw==,iv:xNv1jB29gB6xasBwKC71/qetP0s2lDpKIBGMV/NJ78A=,tag:437fvzl+GR/aVnrYDRZo0w==,type:bool]
        value: ENC[AES256_GCM,data:nEJ/tf089GQP3cYta92O9wzdfkmsRU8B7OCCroJtyn5icnwzGPw9ITtq0BM=,iv:YfuS/bBNmGbf1cDs1wApmwxmroJcQ8HpEe49f2bIeo0=,tag:yIQ/sBnSAV76Jv5a0IEVxA==,type:str]
    homelab:autheliaPostgresPassword:
        secret: ENC[AES256_GCM,data:ATnOug==,iv:ZgjmQbgBjnN4Dy/K0qFeXIux77OArrpaKiBu9v65Gac=,tag:SXcFs9ExRqLTbD//d2eNiw==,type:bool]
        value: ENC[AES256_GCM,data:OaLezvEOOsMA5btGT1+8/yx7JNCLnxITszCfCcXrlcHRXElxWoJf0mx8ios=,iv:rb2BH0Gta7J1UPDOjSX+5hdXhOLqE9Vp5FOeQvnpGzw=,tag:xAlydHJ+qmUYuvfXeb+SCA==,type:str]
    homelab:autheliaSessionSecret:
        secret: ENC[AES256_GCM,data:0FngdA==,iv:FQjUVVN9a/OftvJDlCaE+FnTZKC46q2DYMR6QyKf8Qc=,tag:eOPmTjd6EFE4T0rrzgKXhg==,type:bool]
        value: ENC[AES256_GCM,data:hccFTj7Nzo3D2Ivf/griiBcdJaD7NRhKQPDAjokUogAEQQ53Yvjo4hoLXsw=,iv:haXQ+mwPfckM+6fX2PXFlZIngPQcvGkR2yRr5iBRYKI=,tag:z8SEAsH6cVaAPnYxIMgz7w==,type:str]
    homelab:autheliaStorageEncryptionKey:
        secret: ENC[AES256_GCM,data:JZlohg==,iv:X/VtHMSiJ+zycowd1YC/11PTJfN0BaUE/XlEqczONRc=,tag:Wj3sjlkLB7oot38uE5qXQA==,type:bool]
        value: ENC[AES256_GCM,data:ksE=,iv:Y03V6PHv5/kAeC8vtTkTrcT3MEz2i4nEA0hnIlUL72s=,tag:UV5TnmXAofEa5zP2N2UiVw==,type:str]
    homelab:cloudflareAccountId:
        value: ENC[AES256_GCM,data:Ps2fNv2/PdRWkMV+3UVGIrIduuWB9NPAPrb9hGnYwjA=,iv:j3TQGmnPPVjmS/jflHdP5kEUc8Oup96rOGBrj2f8Dt0=,tag:AbNJE1IyAZGTkDTNhIARnQ==,type:str]
    homelab:cloudflareZoneId:
        value: ENC[AES256_GCM,data:P/rvIxDCb5FE1UMUyoiz8jyUH5UaXW4GLyZCkNREJUU=,iv:0HMPs7lAYFxWdeM51ovhbSumlIZjj6dGympOJuEVhFM=,tag:UjWvAAwERL+p/WD1P2PU0A==,type:str]
    homelab:container-registry:
        value: ENC[AES256_GCM,data:r4Br1/fbu/8alzMElUO2uRQ9ssbMVd0dw3YMfNBs0WsZce6rdd/Mix1g3KscesH6ucb25IWcNzuxt5QjnmD1CUp8btBR,iv:YigUo0L3/lRXLZy2bYEmQT0u5/nR0owWW2c6EtVILV0=,tag:Z2K9ZNF86OiYbPLR0NLUsA==,type:str]
    homelab:domain:
        value: ENC[AES256_GCM,data:GLgkRc7EK41a7+j2,iv:vSyoZ4oTRKByPsictWcBLgDG4HKmbl3TWhp7WSJSrpg=,tag:8otlJ5Yrwhzo0nBDMGwsrQ==,type:str]
    homelab:email:
        value: ENC[AES256_GCM,data:gBb49IKG7Jt23rR204YdQSYk,iv:tNZ6XFtbRaCK2VOqkw0RU1buIPJy0SR8rwmKt4NvAG0=,tag:6p17ejHjeTVmPGr2rm5UqA==,type:str]
    homelab:grafanaAdminPassword:
        secret: ENC[AES256_GCM,data:hYfmkA==,iv:VzyeL9yVAgRiPJFCQCKHnesWbvvxsmRYXMRhUodhoRk=,tag:+bnKFBAZfUh9IJaHlOnS3w==,type:bool]
        value: ENC[AES256_GCM,data:mecRgbepfluI7sFyT7SCFKp22gA=,iv:L8pSp/hj6kkjU8108xsF3/XDtUSgBv/W0ZkLyveVP7o=,tag:sLpZaB/7lzkZrLjn0xtbfQ==,type:str]
    homelab:pulumiAccessToken:
        secret: ENC[AES256_GCM,data:UfYzHQ==,iv:DqsWhS6MV+XMOusMc3RTL91ix8bVIt9i9WwahCkUEVA=,tag:ayIwJRNJuIb3BC0WanpuPg==,type:bool]
        value: ENC[AES256_GCM,data:8kpMmiTnPkYVTcLBy1faJSE+gJEQujx2hrQsHrGzRtB2eba1tuRiUh8+fMY=,iv:LG3TahLi9L5YboDTMVXHagTwcljDulVfmsR8Pk6YOfo=,tag:FDqtrs0taasxXHvOnfNiCA==,type:str]
    homelab:pulumiOrganization:
        value: ENC[AES256_GCM,data:+8g7kBrSzvfI,iv:l1F23+y7+VSjz4mcwI7aG/kuJ9ZnriXmZs3b8NIE99U=,tag:GSDEucgiV40A0wjSCDQ9vg==,type:str]
    longhorn:backupAccessKeyId:
        secret: ENC[AES256_GCM,data:HayPZg==,iv:eGcDx8NTiAC9id7k48ErZAseuQHTTSqJLayQYoh2mGs=,tag:meDwoltI0FIttrfpp/AMNA==,type:bool]
        value: ENC[AES256_GCM,data:9gSz0lWV57r62JZwzcXEdfG5LcBDehhUIuar8ZYCWag=,iv:Lbhsvd55T8oSKwYEjNiKd3BOM6jahyy07YKEZw1uvAI=,tag:lOdTeRBtbvICAT9yQbUxYQ==,type:str]
    longhorn:backupSecretAccessKey:
        secret: ENC[AES256_GCM,data:iW0s1w==,iv:Dr8HE2xBjfqx3wCkVX7n0X5/lc3ItmYGSU51t9iruaM=,tag:8oehwkrxfvuhkv46rSH7TQ==,type:bool]
        value: ENC[AES256_GCM,data:pjZelcJfcQpaNQ8a4nowUf6YXWQCTTHigEKOsefxqZ+Rf90v9whAaiMv4Nrt5ty1ZVkwYR7qPrPP1AVfXo3UyA==,iv:/Y53dyurv0b3VztxhwB6BCuuj4BNVue5P5sYZY63HfA=,tag:rZxa3OPC1HefCaNyZKxDvw==,type:str]
    oauth2-proxy:clientId:
        secret: ENC[AES256_GCM,data:FuZXJQ==,iv:WNQD1zEavDMcpqUwEgTmclX6jqLr1RrmjI0gA0tYd+4=,tag:VfvcNY0N0/NIo+irOum/6w==,type:bool]
        value: ENC[AES256_GCM,data:/WOSuKghPkXFbkrABwjs2fREHaQ=,iv:8GocxyczdrgPBzIgZB0Tc9BoDD701sRcwBX1IkLakXg=,tag:wyCsjsyTcOBjD0wCOgVZBw==,type:str]
    oauth2-proxy:clientSecret:
        secret: ENC[AES256_GCM,data:uIn0Fg==,iv:gjMJR0VdcUreEU+vqFJbH0gzGDL+WgKMXvmM3MSQEnQ=,tag:1/oecA/y+lptDx83MkA7Sg==,type:bool]
        value: ENC[AES256_GCM,data:7YuuHCOCQRPPYYneW7HuYf1z2nL7TVyvMluluCzTlbffbn81qetebw==,iv:ZYeAQUFKr5SOd5CEAdwCwUMIm8KRmPYJKOBSmnxSIyI=,tag:74s2GDNamxSH7AgrCBalzw==,type:str]
    oauth2-proxy:cookieSecret:
        secret: ENC[AES256_GCM,data:SnU8oA==,iv:YI7uM0ozzqaP/0DigVpYVancMmBFwgXsrnkaz3VOyIE=,tag:nPJce28170+J7tGBrVBiyA==,type:bool]
        value: ENC[AES256_GCM,data:dpYB0SVsH5FI5YBZp0wmROnJJijD57jBhxdwHqATbI8=,iv:pFYE80ROhQFHOBnUnRBFfA6bpdMBlXnUM66oHbWRiaU=,tag:b4bJOy44dL13LYT3ygyPWw==,type:str]
    oauth2-proxy:developersClientId:
        secret: ENC[AES256_GCM,data:wZCdaw==,iv:+ii/KXwH0c8wXxWbc6nmOlkTaol3CYYV2jMuMNa/K9g=,tag:MvA1Gp348rApb9GOXM3vdg==,type:bool]
        value: ENC[AES256_GCM,data:0vgVgoq7SZB/kPZsG5DBTld7MGs=,iv:c1bbF9/80Ys1KQ0yPJjvGAYLKsuCfqazcfwaw9cTpxc=,tag:pGzh8DcQ7jgxvC230UYGfg==,type:str]
    oauth2-proxy:developersClientSecret:
        secret: ENC[AES256_GCM,data:OVLkuQ==,iv:eeJInjRo/YBdrKClu47l3hOxN3ccupBV/RW4xyMC1CE=,tag:MHseaj3Qk6YS8ncvfalBmQ==,type:bool]
        value: ENC[AES256_GCM,data:2zeEdnpClF+pHJt1xBJ2e/wVH7s/5ojRMNHqoKQhsyDkdxLM+mNugQ==,iv:X8jHR7HGruFNbU7gR9eHBHvGyQoAv7uwrDwdVkJoU1Y=,tag:cmtWD6Eo064u64WkVPsung==,type:str]
    oauth2-proxy:developersCookieSecret:
        secret: ENC[AES256_GCM,data:0q8Zhg==,iv:7HLzGSoxjnWubPODRk305m5wDF9n3rz4lHbjr6LrvGY=,tag:5KeaL75hsxBO/3/LHg4ovw==,type:bool]
        value: ENC[AES256_GCM,data:qSCcjIXlmP6zeE32gisfgqUA5aaexwCe4etwbaAEfhY=,iv:lKAsreDCwNFunH4TePnvGSqqFV7jDAMfW79MsA2P5zI=,tag:B+vONu9T1DusvQXivcihUA==,type:str]
    oauth2-proxy:provider:
        value: ENC[AES256_GCM,data:j+ZzIO5N,iv:iCTqDDfra2FNUwyqhLIrSZSrWlaT7V/zcshGOmqV2U8=,tag:aCnNbJpM5gng8OtdzQpaBg==,type:str]
esc_environments:
    mrsimpson_homelab_dev:
        name: ENC[AES256_GCM,data:M6M1WsUrUnuBtVK6vX4ynZL5321I,iv:aazyp+kIwKmogJapIEp0tUEEx46K5/+FM7xHesLGf7Y=,tag:QQVEOQeltkj3oI99JDpq/Q==,type:str]
        values:
            github-credentials:
                token: ENC[AES256_GCM,data:2cnjJPY1U/bg/Cq8j4OcpvmO4+Oes/MAdmFbg1v+Bqeba51nW0Z0/w==,iv:/hJaDuTZDbH6SuGM2iO1v0cjG9fAOzs8YeyHOyjlOtA=,tag:rt2eCCu1tjc7RS5KN8PMtw==,type:str]
                username: ENC[AES256_GCM,data:dYRwp+3rz0n6,iv:VD6GgLAcHUUsTRzg+DJ3lQghekT9zLEEAKRtTIj4beU=,tag:JGVDWHp/KbB5XW1OJt2IgA==,type:str]
            github-token: ENC[AES256_GCM,data:66AW9CZyAv2WgKFKjgY0j0HScOZH0ocGNHIfCEXOfsHPqF86SsbNrw==,iv:I9CDFCa9iS/RsxqxrQCcxmqNkA8XpeEnpGvbIQJ9Eq8=,tag:3noVPXrdyz5HvTCA4pXvXA==,type:str]
            github-username: ENC[AES256_GCM,data:OFv+WJhINYqO,iv:mCk9lYpkyqhmcOeGPS7v8x2kH3fqBVMqzeF9Y4izzsM=,tag:NtlehNyoYkZ1cPi92Otdfg==,type:str]
            matrix-bot-access-token: ENC[AES256_GCM,data:9Fymz4LCm6qRYueASnvfcuA+eAhGiKeaJ4Kx3IClzfg=,iv:VVlv4xr/IglaBewubapv49Arb+C4tJ4YQzVgJmNwh3s=,tag:CdgQd459CUNP9S4qKlDL3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYy9vRVRLT0lGanhIV0ll
            S1had2RuSWphdkV2Z0k5TFAwQUNGdHZLWEI0CjJBdjFETk8zcFQvK3lFOUdkMlhM
            emdXVHpmZFhLYSs2bXpXU1ZLakZjQ0EKLS0tIFRHRmhTZS9sSExPaWxmcVdwQVYx
            dzljS2pmbG9pTk9WU3RhQm5jNlp1KzQK8Rj5vj4QndNTYEbF0QgddEJ4YSnLXRyG
            RzwFaTL43iasBsK5o/6dVB0or5oikftW/qcIe9e2cyeGCtaqalT5/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fleshqd626lkpwd6p5y3wwwuz99ky0e5s6jwr07ssvezxn4924uq02qerp
    lastmodified: "2026-10-03T06:24:52Z"
    mac: ENC[AES256_GCM,data:jQgTCFhkkvEHXscLEhMMUkjvGFeS6eqskdCp7sU6mR4Xb3jfCMqbV7hObYXA2oFeboZUNIdu94Hkk0jg4q9am/M1W7Z4sqIKKmAVhoi7qXL5TXrknMyIDh/uCoBgLtcqU35pIKfT+WPRxGqrdMZNae65w/PNvW2QWUvGgemmq0w=,iv:IgKZ3DIAvg/E7aMhtrtNl7MWa832egsb0Zbch83FPSI=,tag:vZrCHeTeOU5IQdcN3P9rjw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
